name: Test LocalGov Microsites localgovdrupal/localgov_microsites drupal-profile

on:
  push:
    branches:
      - '4.x'
  pull_request:
    branches:
      - '4.x'
  workflow_dispatch:

jobs:
  tests:
    uses: localgovdrupal/localgov_shared_workflows/.github/workflows/test-microsites.yml@feature/1.x/use-phpunit
    with:
      project: 'localgovdrupal/localgov_microsites'
      project_path: 'web/profiles/contrib/localgov_microsites'
